#ifndef __DEFINES_H__
#define __DEFINES_H__

#define CELL_WIDTH 32
#define CELL_HEIGHT 16

#define MAP_SIZE 24

#define MAP_RENDER_X_OFFSET ( ( SCREEN_WIDTH - ( CELL_WIDTH * MAP_SIZE ) ) / 2 )
#define MAP_RENDER_Y_OFFSET 425

#define SPRITE_TILE_WIDTH 13
#define SPRITE_TILE_HEIGHT 8

#define MAX_TILES 1024
#define MAX_ISO_OBJECTS 1024
#define MAX_ENTITIES 256
#define MAX_PROJECTILES 256
#define MAX_GROUND_ITEMS 256
#define ISO_RENDER_SPEED 250

#define ROOT2OVER2 0.7071067812

#define INDEX_3( x, y, z, width, height ) ( ( z * ( width * height ) )\
    + ( y * height ) + x )

#define INDEX_2( x, y, height ) ( ( x * height ) + y )

enum
{
  LAYER_BACKGROUND = 0,
  LAYER_MID = 8,
  LAYER_FOREGROUND = 15,
  LAYER_MAX
};

enum
{
  FACING_NONE = 0,
  FACING_NORTH,
  FACING_NORTH_EAST,
  FACING_EAST,
  FACING_SOUTH_EAST,
  FACING_SOUTH,
  FACING_SOUTH_WEST,
  FACING_WEST,
  FACING_NORTH_WEST,
  FACING_MAX
};

enum
{
  TILE_GROUND = 0, //128 different ground tiles
  TILE_WALL = 128, //128 wall tiles
  TILE_WATER = 160, //32 water tiles
  TILE_MAX = 256  //
};

enum
{
  STATIC_OBJECT = 0,
  ANIMATED_OBJECT,
};

enum
{
  STATE_IDLE = 0,
  STATE_RUN,
  STATE_ATTACK,
  STATE_CONFUSED,
  STATE_MAX,
};

enum
{
  FOOD_BLUE_DRINK = 0,
  FOOD_ORANGE_DRINK,
  FOOD_GREEN_DRINK,
  FOOD_RED_DRINK,
  FOOD_BURGER,
  FOOD_FRIES,
  FOOD_WHITE_CAKE,
  FOOD_CHOCOLATE_CAKE,
  FOOD_CHOCOLATE_BAR,
  FOOD_STRAWBERRY_CHOCOLATE_BAR,
  FOOD_WHITE_CHOCOLATE_BAR,
  FOOD_GRILLED_CHEESE,
  FOOD_STRAWBERRY_ICE_CREAM_CONE,
  FOOD_MINT_ICE_CREAM_CONE,
  FOOD_VANILLA_ICE_CREAM_CONE,
  FOOD_CHOCOLATE_ICE_CREAM_CONE,
  FOOD_APPLE,
  FOOD_ORANGE,
  FOOD_PEAR,
  FOOD_BLUEBERRY,
  FOOD_GRAPE,
  FOOD_PEACH,
  FOOD_BLACKBERRY,
  FOOD_BANANA,
  FOOD_MILK,
  FOOD_STRAWBERRY_MILK,
  FOOD_CHOCOLATE_MILK,
  FOOD_BLUE_CANDY,
  FOOD_PURPLE_CANDY,
  FOOD_RED_CANDY,
  FOOD_PANCAKES,
  FOOD_SALAD,
  FOOD_MAX
};

enum
{
  SLIME_RED = 0,
  SLIME_BLUE,
  SLIME_GREEN,
  SLIME_GOLD,
};

#endif

